name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]  # Trigger deployment on main branch updates

permissions:
  contents: write  # Allow write permissions to the repository contents

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Adjust if files are in a subdirectory
